name: aqsolpred
channels:
- chemplot
- conda-forge
- defaults
dependencies:
    - rdkit
    - chemplot==1.0.2
    - pip
    - pip: 
        - streamlit==0.83.0
        - pandas==1.1.3
        - bokeh==2.2.3
