name: aqsolpred
channels:
- conda-forge
- defaults
dependencies:
    - libgcc=5.2.0
    - rdkit
    - pip
    - pip:
        - streamlit==0.84.0
        - chemplot==1.1.1
        - pandas==1.1.3
        - bokeh==2.2.3
        - shillelagh==1.0.5
        - google-auth==2.3.3
