name: aqsolpred
channels:
- rdkit
- conda-forge
- defaults
dependencies:
    - libgcc=5.2.0
    - rdkit
    - pip
    - pip: 
        - streamlit==0.81.0
        - chemplot==1.0.2
        - pandas==1.1.3
        - bokeh==2.2.3
