name: aqsolpred
channels:
- rdkit
- conda-forge
- defaults
dependencies:
    - libgcc=5.2.0
    - rdkit
    - pip
    - pip: 
        - streamlit==0.78.0
        - chemplot==0.1.2
        - mordred==1.2.0
        - Pillow==8.1.0
        - pandas==1.1.3
        - scipy==1.5.2
        - numpy==1.19.2
        - bokeh==2.2.3
        - gspread==3.7.0
        - oauth2client==4.1.3
        - oauthlib==3.1.0
        - pytz==2020.5
