channels:
- conda-forge
- defaults
dependencies:
    - libgcc=5.2.0
    - chemplot==1.2.0
    - pip
    - pip:
        - streamlit==1.2.0
        - bokeh==2.4.1
        - pandas==1.3.5
        - gspread==5.0.0
        - google-auth==2.3.3