name: chemplot_web_app
channels:
- conda-forge
- defaults
dependencies:
    - libgcc
    - streamlit
    - chemplot >=1.2.0
    - pandas
    - bokeh <=2.4.1
    - pip
    - pip:
        - gspread
        - google-auth
